#!/bin/bash -e

docker_run() {
  # This currently fails with this cryptic error:
  #
  #    rosetta error: failed to open elf at
  #    bundle: Child exited for unknown reason! (wstatus == 5)
  #
  # Note the empty string at the end of that first line; this is as it appears
  # in the test.
  /src/build_output/static/bundle
}

cmd="./bundle_test in_docker $@"
if [[ "$1" == "in_docker" ]]; then
  shift
  docker_run
  exit 0
fi

if [[ "$1" == "debug" ]]; then
  cmd=bash
fi

source ./docker/common.inc
image=${build_image}:${build_tag}

CWD=$(pwd)
docker run --rm -it \
  --platform=linux/amd64 \
  --mount "type=bind,src=${CWD}/build_output,dst=/src/build_output,readonly" \
  --mount "type=bind,src=${CWD}/bundle_test,dst=/src/bundle_test,readonly" \
  $image \
  $cmd
